name = "discord-oidc"
main = "worker.js"
compatibility_date = "2022-12-24"

kv_namespaces = [
  { binding = "KV", id = "2b26f69504214e0fb543ed29d29b8cdf", preview_id = "b43c22430b5240dea89cd6cc350d3946" }
]